♻️ make player api declarative
audapolis/audapolis pull request #223
Opened 2022-01-12 17:19 UTC by anuejn

this moves complexity into the player by giving it just the wanted state. this simplifies redux reducer code a lot.

2022-01-12 17:21 UTC, anuejn commented
this should close #142 by not making it nescessary to supress such things anymore. they are now correctly handeled.

2022-01-13 22:28 UTC, pajowu requested changes

2022-01-13 22:28 UTC, pajowu commented on app/src/core/player.ts
> +    const lastRenderItem = this.renderItems[this.renderItems.length - 1];
maybe move to function

2022-01-13 22:28 UTC, pajowu commented on app/src/core/player.ts
> +      const startTime = +new Date();
please comment on `+new Date()`

2022-01-13 22:28 UTC, pajowu commented on app/src/core/player.ts
> +      const callback = () => {
can we deduplicate the callbacks for this and artificial silence

2022-01-13 23:20 UTC, pajowu approved these changes

2022-01-13 23:38 UTC, merged