fix cursor movement
audapolis/audapolis pull request #224
Opened 2022-01-12 23:22 UTC by anuejn

- ♻️ make player api declarative
- 🧪️ add test for editor/goLeft
- 🐛️ fix cursor not being re-positioned
- 🐛️ fix itertools.dropwhile
- 🐛️ fix cursor left / right movement
- 🧪️ add tests for cursor left / right movement

2022-01-12 23:23 UTC, anuejn commented
this should close #217

2022-01-13 17:21 UTC, anuejn commented
this depends on #221

2022-01-13 22:43 UTC, pajowu requested changes

2022-01-13 22:43 UTC, pajowu commented on app/src/util/itertools.ts
> +    if (!dropping) {
Nice catch, I did not know that generators are not reusable (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#do_not_reuse_generators). Please also update `takewhile`

2022-01-13 22:43 UTC, pajowu commented on app/src/state/editor/play.ts
> +  // if we are at the beginning of a paragraph, we should put the cursor at the end of the paragraph before
```suggestion
  // if we are at the beginning of a paragraph, we should put the cursor at the end of the previous paragraph
```

(I had to read this sentence twice, I personally think this makes it clearer)

2022-01-13 23:53 UTC, pajowu approved these changes

2022-01-14 00:14 UTC, merged