developer docs improvements
audapolis/audapolis pull request #247
Opened 2022-01-17 21:51 UTC by anuejn

- 📃️ doc: clarify server/README.md
- 📃️ doc: hint to server deps in app/README.md
- ☝️ upgrade numpy; document missing wheels
- ⚠️ mute ffmpeg not found warning in backend

2022-01-18 00:02 UTC, pajowu requested changes
Nice, just 1 small remark

2022-01-18 00:02 UTC, pajowu commented on server/README.md
> +Either install poetry using your system package manager or by running.
I think the code for installing poetry should go after this line

2022-01-18 08:26 UTC, jgarplind commented
Nice! I pulled down the branch and verified that all requested improvements are there. Docs are more accurate, and confusing warnings are muted. 🎉

2022-01-22 13:02 UTC, pajowu commented
/rebase

2022-01-22 13:07 UTC, pajowu commented
/rebase

2022-01-22 13:33 UTC, pajowu commented
/rebase

2022-01-22 14:26 UTC, pajowu approved these changes

2022-01-22 14:26 UTC, merged